## Subsetting

Operators use for subsetting objects:

- [    extract elements of object
- [[   extract elements of list/dataframe
- $    extract elements from list/dataframe by name

In [1]:
x <- c("a", "b", "c", "c", "d", "a")

In [2]:
x[1]

[1] "a"

In [3]:
x[2]

[1] "b"

In [4]:
x[1:4]

[1] "a" "b" "c" "c"

In [5]:
x[x > "a"]

[1] "b" "c" "c" "d"

In [7]:
u <- x > "a"
u

[1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE

In [8]:
x[u]

[1] "b" "c" "c" "d"

## Subsetting Lists

In [9]:
x <- list(foo = 1:4, bar =0.6)
x

$foo
[1] 1 2 3 4

$bar
[1] 0.6

In [10]:
x$bar

[1] 0.6

In [11]:
x[["bar"]]

[1] 0.6

In [12]:
x <- list(foo = 1:4, bar = 0.6, bar = "hello")
x[c(1,3)]

$foo
[1] 1 2 3 4

$bar
[1] "hello"

In [13]:
x <- list(foo = 1:4, bar = 0.6, baz = "hello")

In [14]:
name <- "foo"

In [15]:
x[[name]]

[1] 1 2 3 4

In [16]:
x$name

NULL

Double bracket operator can be used to index a list but $ cannot do that.  

In [17]:
x$foo

[1] 1 2 3 4

In [18]:
x <- list(a = list(10, 12, 14), b = c(3.14, 2.81))

In [20]:
x[[c(1,3)]]

[1] 14

In [22]:
x[[1]][[3]]

[1] 14

In [24]:
x[[c(2,1)]]

[1] 3.14

## Subsetting a Matrix

In [26]:
x <- matrix(1:6, 2, 3)

In [27]:
x[1,2]

[1] 3

In [28]:
x[2,1]

[1] 2

In [29]:
x[1,]

[1] 1 3 5

In [30]:
x[,2]

[1] 3 4

In [36]:
# drop = FALSE Preserves the dimensions of the matrix

#(1x1)
x[1, 2, drop = FALSE]

[,1]
[1,] 3

In [37]:
x[1, , drop = FALSE]
#(1x3)

[,1] [,2] [,3]
[1,] 1    3    5

## Partial Matching 

In [39]:
x <- list(aardvark = 1:5)

In [40]:
x$a

[1] 1 2 3 4 5

In [41]:
x[["a"]]

NULL

In [42]:
x[["a", exact = FALSE]]

[1] 1 2 3 4 5

## Removing Missing Values

In [43]:
x <- c(1, 2, NA, 4, NA, 5)
bad <- is.na(x)
x[!bad]

[1] 1 2 4 5

## Subset Multiple NA values from corresponding data

In [44]:
x <- c(1, 2, NA, 4, NA, 5)
y <- c("a", "b", NA, "d", NA, "f")
good <- complete.cases(x,y)
good

[1]  TRUE  TRUE FALSE  TRUE FALSE  TRUE

In [45]:
x[good]

[1] 1 2 4 5

In [46]:
y[good]

[1] "a" "b" "d" "f"

In [ ]:
# let airquality is a dataframe

good <- complete.cases(airquality)

# get rows 1:6

airquality[good, ][1:6, ]

## Vectorized Operations

In [47]:
x <- 1:4; y <-6:9
x+y

[1]  7  9 11 13

In [48]:
x > 2

[1] FALSE FALSE  TRUE  TRUE

In [49]:
x >= 2

[1] FALSE  TRUE  TRUE  TRUE

In [50]:
y == 8

[1] FALSE FALSE  TRUE FALSE

In [51]:
x*y

[1]  6 14 24 36

In [52]:
x/y

[1] 0.1666667 0.2857143 0.3750000 0.4444444

In [53]:
x <- matrix(1:4, 2, 2); y <- matrix(rep(10, 4), 2, 2)

In [54]:
x*y

[,1] [,2]
[1,] 10   30  
[2,] 20   40

In [55]:
x/y

[,1] [,2]
[1,] 0.1  0.3 
[2,] 0.2  0.4

In [57]:
x %*% y   # true matrix multiplication

[,1] [,2]
[1,] 40   40  
[2,] 60   60