## Loop Functions:

- **lapply** : Loop over a list and evaluate a function on each element
- **sapply** ; Same as lapply but try to simplify the result
- **apply** : Apply a function over the margins of an array
- **tapply** : Apply a function over subsets of a vector
- **mapply** : Multivariate version of *lapply*

Useful auxiliary function: **split** (used in conjunction with *lapply*)

## lapply:

In [ ]:
function (X, FUN, ...){
    FUN <- mat.fun(FUN)
    if(!is.vector(X) || is.object(X))
        X <- as.list(X)
    .Internal(lapply(X, FUN))
}

In [1]:
x <- list(a = 1:5, b = rnorm(10))

In [2]:
lapply(x, mean)

$a
[1] 3

$b
[1] 0.1051129

In [3]:
x <- list(a = 1:4, b = rnorm(10), c = rnorm(20,1), d = rnorm(100,5))

In [4]:
lapply(x, mean)

$a
[1] 2.5

$b
[1] 0.03108256

$c
[1] 1.057037

$d
[1] 5.001794

In [5]:
x <- 1:4

In [6]:
lapply(x, runif)

[[1]]
[1] 0.1546568

[[2]]
[1] 0.2524214 0.9502679

[[3]]
[1] 0.4687795 0.3582717 0.7367810

[[4]]
[1] 0.20683871 0.14445371 0.06598847 0.92514458

basically doing runif(x)

In [9]:
x <- 1:4
lapply(x, runif, min = 0, max = 10)

[[1]]
[1] 7.747003

[[2]]
[1] 8.186741 9.454147

[[3]]
[1] 3.1172230 3.9682179 0.8137086

[[4]]
[1] 0.5636960 0.2208993 8.0899931 3.1332432

In [10]:
x <- list(a = matrix(1:4, 2, 2), b = matrix(1:6, 3, 2))

In [11]:
x

$a
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$b
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

## Using anonymous functions:

The following function extracts the first column

In [12]:
lapply(x, function(elt) elt[,1])

$a
[1] 1 2

$b
[1] 1 2 3

This function doesn't exist. it only exists within the context of the lapply. 

## sapply

- Simplifies the output
- If the result is a list, a vecto r is returned
- If result is list with vectors of same length, matrix is returned
- If it can't figure out, then list is returned

In [13]:
x <- list(a = 1:4, b = rnorm(10), c = rnorm(20,1), d = rnorm(100,5))

In [14]:
lapply(x, mean)

$a
[1] 2.5

$b
[1] -0.1485397

$c
[1] 0.6150948

$d
[1] 4.920758

In [15]:
sapply(x, mean)

a          b          c          d 
 2.5000000 -0.1485397  0.6150948  4.9207583

## Apply

- applied over the margins
- applied on rows/columns of matrix
- general arrays
- not faster than loop

In [17]:
str(apply)

function (X, MARGIN, FUN, ...)  


In [2]:
x <- matrix(rnorm(200), 20, 10)

In [3]:
apply(x, 2, mean)
# mean along the columns

[1] -0.04504735 -0.08895068 -0.15265990 -0.14650706 -0.08823293  0.21971242
 [7] -0.38257757 -0.10108996  0.21057943  0.07974621

In [4]:
apply(x, 1, mean)
# mean along the rows

[1] -0.208568364  0.062222992 -0.105373884 -0.678875870 -0.084995037
 [6] -0.016402027  0.180370333 -0.121350323 -0.315711983 -0.316893891
[11]  0.168062481  0.220866630  0.596507102  0.001404198 -0.416734819
[16] -0.076157967  0.452653996 -0.106022282  0.094878566 -0.319934634

Shortcut Functions:

- rowSums = apply(x, 1, sum)
- rowMeans = apply(x, 1, mean)
- colSums = apply(x, 2, sum)
- colMeans = apply(x, 2, mean)

In [6]:
x <- matrix(rnorm(200), 20, 10)

In [8]:
# calculate the 25th and the 75th percentile along the rows:

apply(x, 1, quantile, probs = c(0.25, 0.75))

[,1]       [,2]        [,3]      [,4]       [,5]        [,6]      
25% -1.5221260 -0.04185278 -1.015911 -0.3908364 -0.86665071 -0.2559881
75%  0.6390472  0.85053279  1.078312  0.5439737  0.02564567  0.9952905
    [,7]       [,8]       [,9]       [,10]      [,11]      [,12]     
25% -0.7912073 -0.2597336 -0.7319669 -0.3921775 -0.3022219 -0.4862302
75%  0.1856007  0.6756005  0.2097470  0.8375178  0.3504602  0.2331720
    [,13]      [,14]      [,15]      [,16]      [,17]      [,18]      
25% -0.4843043 -0.6325084 -0.7428567 -0.5166707 -0.2488422 -1.09300027
75%  0.8907894  0.7292796  0.4393425  0.5174418  0.3718593 -0.02136504
    [,19]       [,20]     
25% -0.08303857 -0.8632086
75%  1.40913167  0.9673943

In [9]:
a <- array(rnorm(2*2*10), c(2,2,10))

In [10]:
apply(a, c(1,2), mean)

[,1]        [,2]       
[1,] -0.05557865 -0.05218854
[2,] -0.16845684  0.19109441

In [11]:
rowMeans(a, dim = 2)

[,1]        [,2]       
[1,] -0.05557865 -0.05218854
[2,] -0.16845684  0.19109441

In [13]:
# ^ collapsing the 3rd dimension

## mapply

In [1]:
str(mapply)

function (FUN, ..., MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE)  


multivariate version of lapply, sapply  
applies the function in parallel 

In [2]:
list(rep(1, 4), rep(2, 3), rep(3, 2), rep(4, 1))

[[1]]
[1] 1 1 1 1

[[2]]
[1] 2 2 2

[[3]]
[1] 3 3

[[4]]
[1] 4

In [4]:
mapply(rep, 1:4, 4:1)

[[1]]
[1] 1 1 1 1

[[2]]
[1] 2 2 2

[[3]]
[1] 3 3

[[4]]
[1] 4

Vectorizing a function:

In [6]:
noise <- function(n, mean, sd){
    rnorm(n, mean, sd)
}

In [7]:
noise(5,1,2)

[1] 0.2494716 1.7751813 0.5603514 1.6158507 3.6377138

In [8]:
noise(1:5, 1:5, 2)

[1] 3.3076138 0.9527793 1.8507146 4.2725631 4.5349016

In [9]:
mapply(noise, 1:5, 1:5, 2)

[[1]]
[1] 0.3874087

[[2]]
[1] 3.525729 1.990443

[[3]]
[1] 6.623648 1.759337 1.196364

[[4]]
[1] 3.469057 3.357749 4.792587 5.296343

[[5]]
[1] 5.008070 5.455936 4.294903 5.140043 3.671288

This is essentially the same as: 

In [10]:
list(noise(1,1,2), noise(2,2,2), noise(3,3,2), noise(4,4,2), noise(5,5,2))

[[1]]
[1] 0.470649

[[2]]
[1] 2.760127 4.229887

[[3]]
[1] 3.467998 4.491661 1.957706

[[4]]
[1] 3.619182 2.932733 2.430657 4.378399

[[5]]
[1] 6.184809 6.392138 5.185900 4.843253 3.870613

So, mapply basically allows vectorization of functions which do not allow vectorized inputs.

## Tapply

Apply a function over subsets of a vector

In [12]:
str(tapply)

function (X, INDEX, FUN = NULL, ..., default = NA, simplify = TRUE)  


Example: Take Group means:

In [13]:
x <- c(rnorm(10), runif(10), rnorm(10,1)) # 3 groups of random data
f <- gl(3,10) # set group indices
f

[1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
Levels: 1 2 3

In [14]:
tapply(x, f, mean) # mean across the 3 groups

1          2          3 
-0.1042981  0.4753058  1.2280518

Personally, though, I feel that this is a clumsy method.

In [15]:
tapply(x, f, mean, simplify = FALSE) # returns a list

$`1`
[1] -0.1042981

$`2`
[1] 0.4753058

$`3`
[1] 1.228052

In [17]:
tapply(x, f, range) # calculate the range

$`1`
[1] -2.926907  1.053336

$`2`
[1] 0.2206981 0.9080967

$`3`
[1] -0.2655476  2.5939413

## Split

In [18]:
str(split)

function (x, f, drop = FALSE, ...)  


splits vectors/objects and splits it into groups determined by a factor or list of factors

In [20]:
x <- c(rnorm(10), runif(10), rnorm(10,1)) # 3 groups of random data
f <- gl(3,10) # set group indices
split(x,f) # splitting into 3 parts

$`1`
 [1] -0.814501881  0.956346445  1.073924171  0.088370358  0.982616856
 [6]  0.008077387 -1.146069356  0.267315748 -0.776605102  0.308211798

$`2`
 [1] 0.953753705 0.325896729 0.028464422 0.270244147 0.300187863 0.114053556
 [7] 0.510874593 0.942868591 0.766261166 0.003404646

$`3`
 [1]  1.4205691  0.7547362  0.5072465  2.3975504  0.5017031  2.1566343
 [7] -0.7941281  0.6329698  2.3375322  2.3356189

Common idea: using lapply and split in conjunction

In [21]:
lapply(split(x,f), mean)

$`1`
[1] 0.09476864

$`2`
[1] 0.4216009

$`3`
[1] 1.225043

In [22]:
# same as :
tapply(x, f, mean)

1          2          3 
0.09476864 0.42160094 1.22504325

In [25]:
library(datasets)
head(airquality)

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

In [27]:
s <- split(airquality, airquality$Month) # split according to the months

In [31]:
lapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")]))

$`5`
   Ozone  Solar.R     Wind 
      NA       NA 11.62258 

$`6`
    Ozone   Solar.R      Wind 
       NA 190.16667  10.26667 

$`7`
     Ozone    Solar.R       Wind 
        NA 216.483871   8.941935 

$`8`
   Ozone  Solar.R     Wind 
      NA       NA 8.793548 

$`9`
   Ozone  Solar.R     Wind 
      NA 167.4333  10.1800

In [32]:
sapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")])) #simplifies the results

5        6         7          8        9       
Ozone         NA        NA         NA       NA       NA
Solar.R       NA 190.16667 216.483871       NA 167.4333
Wind    11.62258  10.26667   8.941935 8.793548  10.1800

In [33]:
sapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")], na.rm = TRUE)) #remove missing values

5         6         7          8          9        
Ozone    23.61538  29.44444  59.115385  59.961538  31.44828
Solar.R 181.29630 190.16667 216.483871 171.857143 167.43333
Wind     11.62258  10.26667   8.941935   8.793548  10.18000

Splitting on More than one level:

In [34]:
x <- rnorm(10)
f1 <- gl(2,5)
f2 <- gl(5,2)
f1

[1] 1 1 1 1 1 2 2 2 2 2
Levels: 1 2

In [35]:
f2

[1] 1 1 2 2 3 3 4 4 5 5
Levels: 1 2 3 4 5

In [36]:
interaction(f1,f2)

[1] 1.1 1.1 1.2 1.2 1.3 2.3 2.4 2.4 2.5 2.5
Levels: 1.1 2.1 1.2 2.2 1.3 2.3 1.4 2.4 1.5 2.5

In [38]:
str(split(x, list(f1,f2)))

List of 10
 $ 1.1: num [1:2] -0.0785 -0.7572
 $ 2.1: num(0) 
 $ 1.2: num [1:2] 1.17 -1.31
 $ 2.2: num(0) 
 $ 1.3: num 1.14
 $ 2.3: num -0.232
 $ 1.4: num(0) 
 $ 2.4: num [1:2] -1.454 -0.747
 $ 1.5: num(0) 
 $ 2.5: num [1:2] 0.877 -0.662


In [41]:
str(split(x, list(f1,f2), drop = TRUE)) # drop the empty levels

List of 6
 $ 1.1: num [1:2] -0.0785 -0.7572
 $ 1.2: num [1:2] 1.17 -1.31
 $ 1.3: num 1.14
 $ 2.3: num -0.232
 $ 2.4: num [1:2] -1.454 -0.747
 $ 2.5: num [1:2] 0.877 -0.662
