# Getting Started with R

## Entering Input

In [3]:
x <- 1
print(x)

[1] 1


In [4]:
msg <- "hello"

In [8]:
x <- 1:20
x

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

# Data Types

atomic classes:

* Character
* Numeric
* integer
* Complex
* logical


Object: Vector

create with **vector()** function

## Numbers: 

- Double precision real numbers by default. 
- Integer: 1L
- infinity: **Inf**
- not a number: **NaN**


## Attributes:

- names, dimnames
- dimensions
- class
- length
- others

function: **attributes()** allows to set/modify attributes

## Creating Vectors:

In [9]:
x <- c(0.5,0.6)
x <- c(TRUE,FALSE)
x <- c(T,F)
x <- c("a", "b", "c")
x <- 9:29
x <- c(1+0i, 2+4i)

In [10]:
x <- vector("numeric", length = 10)
x

[1] 0 0 0 0 0 0 0 0 0 0

## Mixing Objects:

In [11]:
y <- c(1.7, "a")    ## LCD -- Character

In [12]:
y <- c(TRUE, 2)     ## Numeric Vector, True -> 1

In [13]:
y <- c("a", TRUE)   ## LCD -- Character

When mixing different objects, coercion occurs.

## Explicit Coercion:


In [14]:
x <- 0:6

In [15]:
class(x)

[1] "integer"

In [16]:
as.numeric(x)

[1] 0 1 2 3 4 5 6

In [17]:
as.character(x)

[1] "0" "1" "2" "3" "4" "5" "6"

In [18]:
as.logical(x)

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

### Nonsensical coercion results in NA

In [19]:
x <- c("a", "b", "c")
as.numeric(x)

Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"

[1] NA NA NA

## Lists:

List is like a vector, but can carry around different types of data, unlike vector, where coercion occurs.

In [20]:
x <- list(1, "a", TRUE, 1+4i)
x

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1+4i

## Matrices

Vectors with 2 dimensions

In [21]:
m <- matrix(nrow = 2, ncol = 3)
m

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [23]:
dim(m)

[1] 2 3

In [24]:
attributes(m)

$dim
[1] 2 3

In [25]:
m <- matrix(1:6, nrow = 2, ncol = 3)
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [26]:
m <- 1:10
m

[1]  1  2  3  4  5  6  7  8  9 10

In [27]:
dim(m) <- c(2,5)
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [32]:
x <- 1:3
y <- 10:12

In [31]:
cbind(x,y)

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

In [30]:
rbind(x,y)

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

## Factors

Used to represent categorical data. 

-treated by modelling functions like **lm()** and **glm()**

In [39]:
x <- factor(c("yes", "yes", "no", "yes", "no" ))
x

#by default the levels are set by alphabetical order

[1] yes yes no  yes no 
Levels: no yes

In [35]:
#frequency count
table(x)

x
 no yes 
  2   3 

In [36]:
#strips out the classes
unclass(x)

[1] 2 2 1 2 1
attr(,"levels")
[1] "no"  "yes"

In [38]:
#setting the levels

x <- factor(c("yes", "yes", "no", "yes", "no"), levels = c("yes", "no"))
x

[1] yes yes no  yes no 
Levels: yes no

## Missing Values:

- is.na() # Check if na
- is.nan() # Check if nan
- NA   # Not Applicable
- NaN  # Not a Number

In [40]:
x <- c(1, 2, NA, 10, 3)
is.na(x)

[1] FALSE FALSE  TRUE FALSE FALSE

In [41]:
is.nan(x)

[1] FALSE FALSE FALSE FALSE FALSE

In [42]:
x <- c(1, 2, NaN, NA, 3)

In [43]:
is.na(x)

[1] FALSE FALSE  TRUE  TRUE FALSE

In [44]:
is.nan(x)

[1] FALSE FALSE  TRUE FALSE FALSE

## Data Frames

- used to store tabular data
- every column has the same length but can store different types
- row.names -> assign names to rows
- read.table() & read.csv() -> read in data
- data.matrix() -> export as matrix


In [47]:
x <- data.frame(foo = 1:4, bar = c(T, T, F, F))
x

foo bar  
1 1    TRUE
2 2    TRUE
3 3   FALSE
4 4   FALSE

In [48]:
nrow(x)

[1] 4

In [49]:
ncol(x)

[1] 2

## Names:

R objects can have names

In [50]:
x <- 1:3

In [51]:
names(x)

NULL

In [52]:
names(x) <- c("foo", "bar", "norf")
x

foo  bar norf 
   1    2    3

In [53]:
names(x)

[1] "foo"  "bar"  "norf"

Lists can also have names.

In [54]:
x <- list(a = 1, b = 2, c = 3)
x

$a
[1] 1

$b
[1] 2

$c
[1] 3

matrices:

In [55]:
m <- matrix(1:4, nrow = 2, ncol = 2)
dimnames(m) <- list(c("a", "b"), c("c", "d"))
m

c d
a 1 3
b 2 4